//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações a este ficheiro poderão provocar um comportamento incorrecto e perder-se-ão se
//     o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPessoas.wsPessoas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsPessoas.WsPessoaSoap")]
    public interface WsPessoaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLivros", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClsDados))]
        AppPessoas.wsPessoas.Livro[] GetLivros();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLivros", ReplyAction="*")]
        System.Threading.Tasks.Task<AppPessoas.wsPessoas.Livro[]> GetLivrosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLivro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClsDados))]
        AppPessoas.wsPessoas.Livro GetLivro(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLivro", ReplyAction="*")]
        System.Threading.Tasks.Task<AppPessoas.wsPessoas.Livro> GetLivroAsync(int i);
    }
    
    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Livro : ClsDados {
    }
    
    /// <observações/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Livro))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class ClsDados : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int iSBNField;
        
        private string nomeField;
        
        private string tituloField;
        
        private int precoCompraField;
        
        private int dataField;
        
        private int pVPField;
        
        private int nColecaoField;
        
        private string ramoField;
        
        private string disponibilidadeField;
        
        private int margemVendaField;
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ISBN {
            get {
                return this.iSBNField;
            }
            set {
                this.iSBNField = value;
                this.RaisePropertyChanged("ISBN");
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("Nome");
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("Titulo");
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int PrecoCompra {
            get {
                return this.precoCompraField;
            }
            set {
                this.precoCompraField = value;
                this.RaisePropertyChanged("PrecoCompra");
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int PVP {
            get {
                return this.pVPField;
            }
            set {
                this.pVPField = value;
                this.RaisePropertyChanged("PVP");
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int NColecao {
            get {
                return this.nColecaoField;
            }
            set {
                this.nColecaoField = value;
                this.RaisePropertyChanged("NColecao");
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Ramo {
            get {
                return this.ramoField;
            }
            set {
                this.ramoField = value;
                this.RaisePropertyChanged("Ramo");
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Disponibilidade {
            get {
                return this.disponibilidadeField;
            }
            set {
                this.disponibilidadeField = value;
                this.RaisePropertyChanged("Disponibilidade");
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int MargemVenda {
            get {
                return this.margemVendaField;
            }
            set {
                this.margemVendaField = value;
                this.RaisePropertyChanged("MargemVenda");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsPessoaSoapChannel : AppPessoas.wsPessoas.WsPessoaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsPessoaSoapClient : System.ServiceModel.ClientBase<AppPessoas.wsPessoas.WsPessoaSoap>, AppPessoas.wsPessoas.WsPessoaSoap {
        
        public WsPessoaSoapClient() {
        }
        
        public WsPessoaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsPessoaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsPessoaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsPessoaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AppPessoas.wsPessoas.Livro[] GetLivros() {
            return base.Channel.GetLivros();
        }
        
        public System.Threading.Tasks.Task<AppPessoas.wsPessoas.Livro[]> GetLivrosAsync() {
            return base.Channel.GetLivrosAsync();
        }
        
        public AppPessoas.wsPessoas.Livro GetLivro(int i) {
            return base.Channel.GetLivro(i);
        }
        
        public System.Threading.Tasks.Task<AppPessoas.wsPessoas.Livro> GetLivroAsync(int i) {
            return base.Channel.GetLivroAsync(i);
        }
    }
}
