//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSServicos.WSPrecos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSPrecos.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name tipo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetExameValor", ReplyAction="*")]
        WSServicos.WSPrecos.GetExameValorResponse GetExameValor(WSServicos.WSPrecos.GetExameValorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetExameValor", ReplyAction="*")]
        System.Threading.Tasks.Task<WSServicos.WSPrecos.GetExameValorResponse> GetExameValorAsync(WSServicos.WSPrecos.GetExameValorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExameValorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExameValor", Namespace="http://tempuri.org/", Order=0)]
        public WSServicos.WSPrecos.GetExameValorRequestBody Body;
        
        public GetExameValorRequest() {
        }
        
        public GetExameValorRequest(WSServicos.WSPrecos.GetExameValorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetExameValorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tipo;
        
        public GetExameValorRequestBody() {
        }
        
        public GetExameValorRequestBody(string tipo) {
            this.tipo = tipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExameValorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExameValorResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSServicos.WSPrecos.GetExameValorResponseBody Body;
        
        public GetExameValorResponse() {
        }
        
        public GetExameValorResponse(WSServicos.WSPrecos.GetExameValorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetExameValorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public float GetExameValorResult;
        
        public GetExameValorResponseBody() {
        }
        
        public GetExameValorResponseBody(float GetExameValorResult) {
            this.GetExameValorResult = GetExameValorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WSServicos.WSPrecos.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WSServicos.WSPrecos.WebService1Soap>, WSServicos.WSPrecos.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSServicos.WSPrecos.GetExameValorResponse WSServicos.WSPrecos.WebService1Soap.GetExameValor(WSServicos.WSPrecos.GetExameValorRequest request) {
            return base.Channel.GetExameValor(request);
        }
        
        public float GetExameValor(string tipo) {
            WSServicos.WSPrecos.GetExameValorRequest inValue = new WSServicos.WSPrecos.GetExameValorRequest();
            inValue.Body = new WSServicos.WSPrecos.GetExameValorRequestBody();
            inValue.Body.tipo = tipo;
            WSServicos.WSPrecos.GetExameValorResponse retVal = ((WSServicos.WSPrecos.WebService1Soap)(this)).GetExameValor(inValue);
            return retVal.Body.GetExameValorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSServicos.WSPrecos.GetExameValorResponse> WSServicos.WSPrecos.WebService1Soap.GetExameValorAsync(WSServicos.WSPrecos.GetExameValorRequest request) {
            return base.Channel.GetExameValorAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSServicos.WSPrecos.GetExameValorResponse> GetExameValorAsync(string tipo) {
            WSServicos.WSPrecos.GetExameValorRequest inValue = new WSServicos.WSPrecos.GetExameValorRequest();
            inValue.Body = new WSServicos.WSPrecos.GetExameValorRequestBody();
            inValue.Body.tipo = tipo;
            return ((WSServicos.WSPrecos.WebService1Soap)(this)).GetExameValorAsync(inValue);
        }
    }
}
